server:
  port: 8081

spring:
  application:
    name: customer

  datasource:
    url: jdbc:postgresql://localhost:9040/customer
    username: postgres
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

  zipkin:
    base-url: http:localhost:9411


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka